root:
  askformore: false
  autoimport: true
  autosync: false
  cliptimeout: 45
  noconfirm: true
  nopager: false
  path: /Users/erkand/.password-store
  safecontent: false
  usesymbols: false
  nocolor: false
mounts: {}
version: 1.6.11
